ARBUSDT: {enabled: true, rr: 5.5}
CRVUSDT: {enabled: true, rr: 7.0}
ENAUSDT: {enabled: true, rr: 2.0}
LTCUSDT: {enabled: true, rr: 3.0}
MNTUSDT: {enabled: true, rr: 3.0}
NTRNUSDT: {enabled: true, rr: 5.5}
OPUSDT: {enabled: true, rr: 6.0}
PAXGUSDT: {enabled: true, rr: 8.0}
SHIB1000USDT: {enabled: true, rr: 4.5}
VIRTUALUSDT: {enabled: true, rr: 6.0}
